# Generated by Django 3.2.5 on 2021-07-31 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apibasics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
